name: CI
on: [push]

jobs:
  rust:
    name: All
    runs-on: [windows-latest]
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust nightly toolchain
        run: rustup set profile default; rustup toolchain install nightly

      - name: Install rust-src
        run: rustup default nightly; rustup component add rust-src

      - name: Build repository
        run: cargo build

      - name: Check formatting
        run: cargo fmt -- --check --verbose

      - name: Run Clippy
        run: cargo clippy

      - name: Run benchmarks/tests
        run: cargo bench
